services:
  gitlab:
    image: gitlab/gitlab-ce:${X_GITLAB_VERSION:-17.0.1}-ce.0
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${X_GITLAB_EXTERNAL_URL:-http://gitlab.example.com}"
        gitlab_rails['gitlab_shell_ssh_port'] = ${X_GITLAB_SSH_PORT:-2222}
        letsencrypt['enabled'] = false
      GITLAB_LOG_LEVEL: warn
    hostname: ${X_GITLAB_HOSTNAME}
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    logging:
      options:
        max-size: 1g
